julia:
  - "1.3"
  - "1"
  - nightly

language: julia

notifications:
  email: false

os:
  - linux
  - osx

script: julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
