name = "BumpStdlibs"
uuid = "23769469-e4e7-4bb7-a710-8b9e5cf687a0"
authors = ["Dilum Aluthge"]
version = "0.1.0-DEV"

[deps]
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"

[compat]
GitHub = "5.1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
